---
gpsTopic: "/vectornav/GPS_INS"
base_link: "base_link"
tfTopic: "/tf"
imuTopic: "/vectornav/IMU"
RTK: "True"
rtkTopic: "/tcpfix"
ptCloudTopic: "/rslidar_points"
semantics: "True"
semanticPtCloudTopic: "/rslidar_semantics"
sourceBags:
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/200803/1/noCam/"
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/200902/noCam/"
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201026/noCam/"
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201118/noCam/"
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201210/noCam/"
mapRegistration: "gps"
radius: "30"
voxelSize: "0.1"
pathOut: "/home/gchahine/mapperOutput/"
autoGenerateMaps: "True"
autoGenerateDist: "15"
Coordinates:
- "49.101827"
- "6.217961"
icpConfig: "/home/gchahine/packages/dream_offline_multi-mapper/icpConfig/icp_param.yaml"
icpInputFilters: "/home/gchahine/packages/dream_offline_multi-mapper/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gchahine/packages/dream_offline_multi-mapper/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
