---
gpsTopic: "/vectornav/GPS_INS"
base_link: "base_link"
tfTopic: "/tf"
imuTopic: "/vectornav/IMU"
RTK: "True"
rtkTopic: "/tcpfix"
ptCloudTopic: "/rslidar_points"
semantics: "True"
semanticPtCloudTopic: "/rslidar_points"
sourceBags:
- "/media/gchahine/94DEB40EDEB3E6A0/10kph/noCam/"
- "/media/gchahine/94DEB40EDEB3E6A0/25kph/noCam/"
mapRegistration: "gps"
radius: "25"
voxelSize: "0.1"
pathOut: "/home/gchahine/mapperOutput/"
Coordinates:
- "49.105249"
- "6.216053"
icpConfig: "/home/gchahine/packages/dream-multi-mapper/icpConfig/icp_param.yaml"
icpInputFilters: "/home/gchahine/packages/dream-multi-mapper/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gchahine/packages/dream-multi-mapper/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
