---

gpsTopic: "/vectornav/GPS_INS"
base_link: "base_link"
tfTopic: "/tf"
imuTopic: "/vectornav/IMU"
ptCloudTopic: "/rslidar_points"

#RTK. If that's your only GPS input, use the gpsTopic above instead and leave this option disabled
RTK: "false"
rtkTopic: "/tcpfix"

#semantics#
semantics: "True"
semanticPtCloudTopic: "/rslidar_semantics"

#inputs
sourceBags:
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/200803/1/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/200902/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201026/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201118/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201210/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210115_2/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210211/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210310/noCam/"

#radius around which the map is accumulated
radius: "70"

#voxel size, for input scans, not for the final map which is not voxelized.
voxelSize: "0.1"
pathOut: "/home/gpu_user/gchahine/mapperOutput/"

#These are only active of autoGenerateMaps is on
autoGenerateMaps: "True"
autoGenerateDist: "27"
closeLoop: "false"
autoWalkingMode: "True"

# this is only used when autoGenerateMaps is off
Coordinates:
- "49.101827"
- "6.217961"

icpConfig: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/icp_param.yaml"
icpInputFilters: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/input_filters.yaml"
boundingBoxFilter: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/bounding_input.yaml"
icpPostFilters: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"


