---
gpsTopic: "/vectornav/GPS_INS"
base_link: "base_link"
tfTopic: "/tf"
imuTopic: "/vectornav/IMU"
RTK: "True"
rtkTopic: "/tcpfix"
ptCloudTopic: "/rslidar_points"
semantics: "True"
semanticPtCloudTopic: "/rslidar_semantics"
sourceBags:
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/Bags/lake_bPearl/200803/1/noCam/"
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/Bags/lake_bPearl/200803/2/noCam/"
- "/run/user/1000/gvfs/sftp:host=tale.georgiatech-metz.fr,user=georges/dream-storage/Backpack_Dataset/Bags/lake_bPearl/200803/3/noCam/"
mapRegistration: "gps"
radius: "30"
voxelSize: "0.1"
pathOut: "/home/gchahine/mapperOutput/"
Coordinates:
- "49.105696"
- "6.216913"
icpConfig: "/home/gchahine/packages/dream-multi-mapper/icpConfig/icp_param.yaml"
icpInputFilters: "/home/gchahine/packages/dream-multi-mapper/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gchahine/packages/dream-multi-mapper/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
