---
gpsTopic: "/vectornav/GPS_INS"
base_link: "base_link"
tfTopic: "/tf"
imuTopic: "/vectornav/IMU"
RTK: "True"
rtkTopic: "/tcpfix"
ptCloudTopic: "/rslidar_points"
semantics: "True"
semanticPtCloudTopic: "/rslidar_semantics"
sourceBags:
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/200803/1/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/200902/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201026/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201118/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/201210/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210115/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210211/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210310/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210409/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210512/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210604/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/on-foot/210701/noCam/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/husky/210705/noCam/"
mapRegistration: "gps"
radius: "35"
voxelSize: "0.1"
pathOut: "/home/gpu_user/gchahine/mapperOutput/"
autoGenerateMaps: "False"
autoGenerateDist: "27"
closeLoop: "True"
Coordinates:
- "49.103779"
- "6.215845"
icpConfig: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/icp_param.yaml"
icpInputFilters: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gpu_user/gchahine/packages/dream-multi-mapper/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
autoWalkingMode: "True"

